# Generated by Django 5.0 on 2023-12-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(choices=[('Ajapnyak', 'Ajapnyak'), ('Avan', 'Avan'), ('Arabkir', 'Arabkir'), ('Davtashen', 'Davtashen'), ('Erebuni', 'Erebuni'), ('Kentron', 'Kentron'), ('Malatia-Sebastia', 'Malatia-Sebastia'), ('Nor Nork', 'Nor Nork'), ('Nork-Marash', 'Nork-Marash'), ('Nubarashen', 'Nubarashen'), ('Shengavit', 'Shengavit'), ('Kanaker-Zeytun', 'Kanaker-Zeytun')], max_length=50)),
                ('is_full', models.BooleanField(default=False)),
                ('fullness_weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
