# Generated by Django 5.0 on 2023-12-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashcansapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrashCans',
            new_name='TrashCan',
        ),
    ]
