# Generated by Django 5.0 on 2023-12-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashcansapi', '0002_rename_trashcans_trashcan'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='trashcan',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trash_cans', to='trashcansapi.district'),
        ),
    ]
