# Generated by Django 5.0 on 2023-12-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashcansapi', '0003_district_alter_trashcan_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
